#!/bin/sh

set -e

echo "VISUALIZER_HOME=$VISUALIZER_HOME"
echo "VISUALIZER_CONFIG=$VISUALIZER_CONFIG"
echo "VISUALIZER_TEMPLATES=$VISUALIZER_TEMPLATES"
echo "VISUALIZER_OUTPUT=$VISUALIZER_OUTPUT"
echo "VISUALIZER_OPTS=$VISUALIZER_OPTS"

ls -l $VISUALIZER_HOME
ls -l $VISUALIZER_HOME/visualizer
ls -l $VISUALIZER_HOME/config
ls -l $VISUALIZER_HOME/templates

$VISUALIZER_HOME/visualizer/bin/visualizer $VISUALIZER_OUTPUT $VISUALIZER_TEMPLATES

rsync -i $VISUALIZER_CONFIG/id_rsa -rltp --chmod=g+r,o+r $VISUALIZER_OUTPUT/ $VISUALIZER_REMOTE
